### ISSUE TITLE
Storing roxygen markup in Rmd?

### ISSUE THREAD

**Issue by jsta** [ropensci/DataPackageR#62]
Here is my situation:

1. Built a data package using `datapackage_skeleton` and `package_build`
2. Manually filled out roxygen docs in `data-raw/documentation.R` and ran `document`

Now, I've made some changes to my base `Rmd` script and want to update the object in `data` using `package_build`. If I do that all of my manually filled roxygen docs have been reset to the template. Is there a way to store these fields in the Rmd or maybe `package_build` can be given an option not to roxygenize?

**Comment by jsta** [comment]
My current workflow is to `git checkout data-raw/documentation.R` then run `document()`.

**Comment by gfinak** [comment]
Are you sure that `documentation.R` is being reset to the template? Because I explicitly don't do that. In fact every package we build has documentation updated incrementally and package_build called multiple times. And the documentation is not reset to the template. The template is created if documentation.R doesn't exist. 
Perhaps there's an edge case here. Can you provide a reprex?

**Comment by jsta** [comment]
My package is at https://github.com/jsta/crp. It has an existing `documentation.R` file that get overwritten if I call `package_build`.

**Comment by gfinak** [comment]
So there's a bug, but I'm not inclined to fix it right now. Basically the issue is that your package and the data object you are creating have the same name. A fix mightl be to check the @doctype tag and do some additional bookkeeping. But it's simpler to just change the name of the data object to something more descriptive and unique (i.e. crp_data). 
Also found a bug related to renaming a data object, you will need to delete the entry for the data object you are renaming in DATADIGEST.
That one I'll open an issue for and fix asap.
Thanks for finding this.

**Comment by gfinak** [comment]
Related / found issue #63  while investigating this..

**Comment by gfinak** [comment]
To address  #62 this we'll validate the `yml` config first and check for data objects that have the same name as the package. We'll provide an error to the user with steps to fix it.
